import 'dart:io';
import 'dart:typed_data';
import 'package:path_provider/path_provider.dart';
import 'package:gal/gal.dart';
import 'package:share_plus/share_plus.dart';

class DownloadService {
  static const _folderName = 'JARVIS_Imagiya';

  /// Save to device gallery
  Future<DownloadResult> saveToGallery(
    List<int> imageBytes,
    String filename,
  ) async {
    try {
      final hasAccess = await Gal.hasAccess(toAlbum: true);
      if (!hasAccess) {
        final granted = await Gal.requestAccess(toAlbum: true);
        if (!granted) {
          return DownloadResult.failure('Gallery permission denied');
        }
      }

      await Gal.putImageBytes(Uint8List.fromList(imageBytes));
      return DownloadResult.success('Saved to gallery');
    } catch (e) {
      return DownloadResult.failure(e.toString());
    }
  }

  /// Save to app documents folder
  Future<DownloadResult> saveToAppDir(
    List<int> imageBytes,
    String filename,
  ) async {
    try {
      final dir = await getApplicationDocumentsDirectory();
      final folder = Directory('${dir.path}/$_folderName');
      if (!await folder.exists()) await folder.create(recursive: true);

      final file = File('${folder.path}/$filename.png');
      await file.writeAsBytes(imageBytes);
      return DownloadResult.success(file.path);
    } catch (e) {
      return DownloadResult.failure(e.toString());
    }
  }

  /// Share image via system share sheet
  Future<void> shareImage(List<int> imageBytes, String prompt) async {
    final tempDir = await getTemporaryDirectory();
    final file = File('${tempDir.path}/imagiya_share.png');
    await file.writeAsBytes(imageBytes);

    // ignore: deprecated_member_use
    await Share.shareXFiles([
      XFile(file.path),
    ], text: 'Generated by JARVIS Imagiya: "$prompt"');
  }

  /// Export CoDesign HTML artifact as file
  Future<DownloadResult> saveHtmlArtifact(
    String htmlContent,
    String filename,
  ) async {
    try {
      final dir = await getApplicationDocumentsDirectory();
      final folder = Directory('${dir.path}/JARVIS_CoDesign');
      if (!await folder.exists()) await folder.create(recursive: true);

      final file = File('${folder.path}/$filename.html');
      await file.writeAsString(htmlContent);
      return DownloadResult.success(file.path);
    } catch (e) {
      return DownloadResult.failure(e.toString());
    }
  }
}

class DownloadResult {
  final bool success;
  final String? path;
  final String? error;

  const DownloadResult._({required this.success, this.path, this.error});

  factory DownloadResult.success(String path) =>
      DownloadResult._(success: true, path: path);
  factory DownloadResult.failure(String error) =>
      DownloadResult._(success: false, error: error);
}
