import 'dart:convert';
import 'package:flutter/foundation.dart';
import '../../core/router/ai_router.dart';

class DiagramService {
  Future<String> generateDiagram(AIRouter router, String userRequest) async {
    final systemPrompt = _buildPrompt(userRequest);
    
    String response = await router.generate(
      userRequest,
      systemPrompt: systemPrompt,
      providerOverride: AIProvider.ollamaCloud,
      modelOverride: 'minimax-m3',
    );
    
    // Extract JSON block using robust substring matching
    String jsonText = response;
    if (response.contains('```json')) {
      jsonText = response.split('```json').last.split('```').first.trim();
    } else if (response.contains('```')) {
      jsonText = response.split('```').last.split('```').first.trim();
    }
    
    // Strip comments and isolate the JSON object bounds
    String cleanJsonText = _stripJsonComments(jsonText).trim();
    final firstBrace = cleanJsonText.indexOf('{');
    final lastBrace = cleanJsonText.lastIndexOf('}');
    if (firstBrace != -1 && lastBrace != -1 && lastBrace > firstBrace) {
      cleanJsonText = cleanJsonText.substring(firstBrace, lastBrace + 1);
    }
    
    try {
      final Map<String, dynamic> parsed = jsonDecode(cleanJsonText);
      final title = parsed['title']?.toString() ?? 'Process Flowchart';
      final description = parsed['description']?.toString() ?? 'Visual representation of the process';
      final List<dynamic> nodesRaw = parsed['nodes'] ?? [];
      
      final List<Map<String, String>> nodes = [];
      for (final n in nodesRaw) {
        if (n is Map) {
          nodes.add({
            'title': n['title']?.toString() ?? '',
            'description': n['description']?.toString() ?? '',
            'icon': n['icon']?.toString() ?? '⚡',
            'color': n['color']?.toString() ?? '#7C5CFC',
          });
        }
      }
      
      return compileHtmlDiagram(title, description, nodes);
    } catch (e) {
      debugPrint("Diagram JSON parsing failed: $e. Falling back to default generation.");
      debugPrint("Attempted clean JSON: $cleanJsonText");
      // Fallback: If JSON fails, treat response as raw HTML/plain string
      if (response.contains('<!DOCTYPE html>') || response.contains('<html>')) {
        return response;
      }
      return compileHtmlFallback(
        title: "Process Blueprint",
        description: "Visual documentation generated by JARVIS AI",
        content: response,
      );
    }
  }

  String compileHtmlFallback({required String title, required String description, required String content}) {
    final cleanContent = content.replaceAll('\n', '<br>');
    return '''
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>$title</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700;800&display=swap');
    body {
      background-color: #080810;
      color: #EEEEFF;
      font-family: 'Outfit', sans-serif;
      margin: 0;
      padding: 24px 16px;
      display: flex;
      flex-direction: column;
      align-items: center;
      min-height: 100vh;
      box-sizing: border-box;
      background-image: 
        linear-gradient(rgba(255, 255, 255, 0.02) 1px, transparent 1px),
        linear-gradient(90deg, rgba(255, 255, 255, 0.02) 1px, transparent 1px);
      background-size: 24px 24px;
    }
    .card {
      width: 100%;
      max-width: 400px;
      background: rgba(18, 18, 30, 0.75);
      border: 1px solid rgba(255, 255, 255, 0.08);
      border-radius: 16px;
      padding: 20px;
      box-sizing: border-box;
      backdrop-filter: blur(12px);
      box-shadow: 0 8px 24px rgba(0, 0, 0, 0.3);
    }
    .title {
      font-size: 18px;
      font-weight: 800;
      color: #FFFFFF;
      margin-bottom: 8px;
    }
    .desc {
      font-size: 12px;
      color: #9090B0;
      margin-bottom: 16px;
      line-height: 1.4;
    }
    .content {
      font-size: 13px;
      color: #EEEEFF;
      line-height: 1.6;
      background: rgba(0, 0, 0, 0.25);
      padding: 12px;
      border-radius: 8px;
      border: 0.5px solid rgba(255, 255, 255, 0.05);
      overflow-x: auto;
      white-space: pre-wrap;
    }
  </style>
</head>
<body>
  <div class="card">
    <div class="title">$title</div>
    <div class="desc">$description</div>
    <div class="content">$cleanContent</div>
  </div>
</body>
</html>
    ''';
  }

  String compileHtmlDiagram(String title, String description, List<Map<String, String>> nodes) {
    final sb = StringBuffer();
    
    sb.writeln('''
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>$title</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700;800&display=swap');
    
    body {
      background-color: #080810;
      background-image: 
        linear-gradient(rgba(255, 255, 255, 0.02) 1px, transparent 1px),
        linear-gradient(90deg, rgba(255, 255, 255, 0.02) 1px, transparent 1px);
      background-size: 24px 24px;
      color: #EEEEFF;
      font-family: 'Outfit', sans-serif;
      margin: 0;
      padding: 24px 16px;
      box-sizing: border-box;
      display: flex;
      flex-direction: column;
      align-items: center;
      min-height: 100vh;
    }
    
    .header {
      text-align: center;
      margin-bottom: 28px;
      width: 100%;
      max-width: 400px;
      animation: fadeInDown 0.6s ease-out;
    }
    
    .subtitle {
      font-size: 9px;
      font-weight: 800;
      letter-spacing: 2px;
      color: #7C5CFC;
      text-transform: uppercase;
      margin-bottom: 6px;
    }
    
    .title {
      font-size: 20px;
      font-weight: 800;
      letter-spacing: -0.5px;
      color: #FFFFFF;
      margin: 0 0 8px 0;
    }
    
    .desc {
      font-size: 11px;
      color: #9090B0;
      line-height: 1.4;
      margin: 0;
    }
    
    .flow-container {
      display: flex;
      flex-direction: column;
      align-items: center;
      width: 100%;
      max-width: 400px;
    }
    
    .card {
      position: relative;
      width: 100%;
      background: rgba(18, 18, 30, 0.75);
      border: 1px solid rgba(255, 255, 255, 0.06);
      border-radius: 16px;
      padding: 16px;
      box-sizing: border-box;
      transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
      cursor: pointer;
      backdrop-filter: blur(12px);
      -webkit-backdrop-filter: blur(12px);
      box-shadow: 0 8px 24px rgba(0, 0, 0, 0.3);
      overflow: hidden;
      display: flex;
      align-items: flex-start;
      animation: slideUpFade 0.6s cubic-bezier(0.16, 1, 0.3, 1) both;
    }
    
    .card::before {
      content: '';
      position: absolute;
      left: 0;
      top: 0;
      bottom: 0;
      width: 4px;
      background: var(--accent-color);
      box-shadow: 0 0 12px var(--accent-color);
    }
    
    .card:hover {
      transform: translateY(-4px) scale(1.02);
      border-color: var(--accent-color);
      box-shadow: 0 16px 36px rgba(0, 0, 0, 0.45), 0 0 20px var(--accent-glow);
    }
    
    .card-icon {
      font-size: 20px;
      margin-right: 14px;
      display: flex;
      align-items: center;
      justify-content: center;
      width: 38px;
      height: 38px;
      background: var(--accent-bg);
      border-radius: 10px;
      flex-shrink: 0;
      border: 0.5px solid var(--accent-border);
    }
    
    .card-content {
      flex-grow: 1;
      display: flex;
      flex-direction: column;
    }
    
    .card-title {
      font-size: 14px;
      font-weight: 700;
      color: #FFFFFF;
      margin-bottom: 4px;
      display: flex;
      align-items: center;
    }
    
    .card-description {
      font-size: 11.5px;
      color: #9090B0;
      line-height: 1.45;
      max-height: 200px;
      overflow: hidden;
      transition: all 0.3s ease;
    }
    
    .card-description.collapsed {
      max-height: 0;
      margin: 0;
      opacity: 0;
    }
    
    .card-toggle {
      font-size: 10px;
      color: #505070;
      margin-left: 8px;
      transition: transform 0.3s ease;
      align-self: center;
    }
    
    .card.is-collapsed .card-toggle {
      transform: rotate(-90deg);
    }
    
    .connector {
      width: 2px;
      height: 24px;
      background: linear-gradient(to bottom, var(--prev-color), var(--next-color));
      position: relative;
      opacity: 0.6;
      margin: 4px 0;
      animation: fadeIn 0.8s ease both;
      overflow: hidden;
    }
    
    .connector::before {
      content: '';
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      height: 6px;
      background: #FFFFFF;
      filter: blur(1px);
      opacity: 0.8;
      border-radius: 50%;
      animation: pulseFlow 2s infinite linear;
    }
    
    .connector::after {
      content: '';
      position: absolute;
      bottom: -1px;
      left: -4px;
      width: 0;
      height: 0;
      border-left: 5px solid transparent;
      border-right: 5px solid transparent;
      border-top: 6px solid var(--next-color);
    }
    
    @keyframes pulseFlow {
      0% { transform: translateY(-6px); opacity: 0; }
      20% { opacity: 1; }
      80% { opacity: 1; }
      100% { transform: translateY(24px); opacity: 0; }
    }
    
    @keyframes fadeInDown {
      from { opacity: 0; transform: translateY(-16px); }
      to { opacity: 1; transform: translateY(0); }
    }
    
    @keyframes slideUpFade {
      from { opacity: 0; transform: translateY(24px); }
      to { opacity: 1; transform: translateY(0); }
    }
    
    @keyframes fadeIn {
      from { opacity: 0; }
      to { opacity: 0.6; }
    }
  </style>
</head>
<body>

  <div class="header">
    <div class="subtitle">Interactive Blueprint</div>
    <div class="title">$title</div>
    <div class="desc">$description</div>
  </div>

  <div class="flow-container">
''');

    for (int i = 0; i < nodes.length; i++) {
      final node = nodes[i];
      final color = node['color'] ?? '#7C5CFC';
      final glow = color.replaceFirst('#', '#3F'); // Glowing accent color
      final icon = node['icon'] ?? '⚡';
      final nodeTitle = node['title'] ?? 'Step ${i + 1}';
      final nodeDesc = node['description'] ?? '';
      final delay = (0.1 * (i + 1)).toStringAsFixed(2);
      
      // Add connector if not the first card
      if (i > 0) {
        final prevColor = nodes[i - 1]['color'] ?? '#7C5CFC';
        sb.writeln('''
    <div class="connector" style="--prev-color: $prevColor; --next-color: $color; animation-delay: ${delay}s;"></div>
''');
      }
      
      sb.writeln('''
    <div class="card" onclick="toggleCard(this)" style="--accent-color: $color; --accent-glow: $glow; --accent-bg: ${color}1C; --accent-border: ${color}33; animation-delay: ${delay}s;">
      <div class="card-step" style="position: absolute; right: 16px; top: 12px; font-size: 9px; font-weight: 800; color: $color; opacity: 0.8; font-family: monospace; letter-spacing: 1.5px;">STAGE 0${i + 1}</div>
      <div class="card-icon">$icon</div>
      <div class="card-content">
        <div class="card-title">$nodeTitle</div>
        <div class="card-description">$nodeDesc</div>
      </div>
      <div class="card-toggle">▼</div>
    </div>
''');
    }

    sb.writeln('''
  </div>

  <script>
    function toggleCard(card) {
      const desc = card.querySelector('.card-description');
      const isCollapsed = desc.classList.toggle('collapsed');
      card.classList.toggle('is-collapsed', isCollapsed);
      
      // Notify parent WebView of height changes
      if (window.flutter_inappwebview) {
        window.flutter_inappwebview.callHandler('heightChanged');
      }
    }
  </script>
</body>
</html>
''');
    
    return sb.toString();
  }

  String _stripJsonComments(String text) {
    final lines = text.split('\n');
    final cleanLines = <String>[];
    for (var line in lines) {
      final commentIdx = line.indexOf('//');
      if (commentIdx != -1) {
        // Ensure double slashes are not part of an http:// or https:// URL protocol
        final urlIdx = line.indexOf('http://');
        final httpsIdx = line.indexOf('https://');
        if (urlIdx == -1 && httpsIdx == -1) {
          line = line.substring(0, commentIdx);
        } else {
          // If URL protocol exists, strip only if // is elsewhere
          if (!line.contains('://') || line.lastIndexOf('//') > line.indexOf('://') + 1) {
            line = line.substring(0, commentIdx);
          }
        }
      }
      cleanLines.add(line);
    }
    return cleanLines.join('\n');
  }

  String _buildPrompt(String userRequest) {
    return '''
You are the JARVIS Process Flowchart & Diagram Architect.
Your task is to design a high-fidelity visual flowchart/diagram for the user's request: "$userRequest".

You must output ONLY a valid JSON object matching the schema below. No markdown wrappers other than ```json if needed, no explanation, no other text.

JSON SCHEMA:
{
  "title": "A concise, engaging title for the process diagram",
  "description": "A high-level summary of what this diagram/architecture represents",
  "nodes": [
    {
      "title": "Name of the step or component",
      "description": "Clear explanation of what occurs in this phase or node",
      "icon": "📦", // Choose a single emoji that represents this specific step/node
      "color": "#00d4ff" // Hex color code for the card border/glow. Choose from:
                         // #00d4ff (cyan), #7c5cfc (purple), #c77dff (lavender), #ffaa44 (orange),
                         // #44ccff (light blue), #ff6b6b (red), #ffd93d (yellow), #4ade80 (green)
    }
  ]
}

Ensure the steps follow a logical sequence from start to finish. Include 4 to 8 nodes to represent the process thoroughly and visually beautifully.
''';
  }
}
