import 'package:flutter/foundation.dart';
import '../../core/router/ai_router.dart';
import 'models/assignment.dart';

class AssignmentProvider extends ChangeNotifier {
  final AIRouter router;
  final List<Assignment> _assignments = [];

  List<Assignment> get assignments => List.unmodifiable(_assignments);
  bool isSyncing = false;

  AssignmentProvider({required this.router});

  void addAssignment(Assignment assignment) {
    _assignments.add(assignment);
    notifyListeners();
  }

  void toggleCompleted(String id) {
    final idx = _assignments.indexWhere((a) => a.id == id);
    if (idx != -1) {
      _assignments[idx] = _assignments[idx].copyWith(isCompleted: !_assignments[idx].isCompleted);
      notifyListeners();
    }
  }

  /// Exports an assignment to Google Docs using the AI Router's built-in GoogleDocsService
  Future<String?> exportToGoogleDoc(Assignment assignment) async {
    isSyncing = true;
    notifyListeners();

    try {
      final docId = await router.googleDocs?.createDoc(
        assignment.title,
        "--- ASSIGNMENT DETAILS ---\n\n"
            "TITLE: ${assignment.title}\n"
            "DUE DATE: ${assignment.dueDate.toString()}\n\n"
            "DESCRIPTION:\n${assignment.description}\n\n"
            "---\nGenerated by JARVIS\n",
      );

      if (docId != null) {
        final idx = _assignments.indexWhere((a) => a.id == assignment.id);
        if (idx != -1) {
          _assignments[idx] = _assignments[idx].copyWith(googleDocId: docId);
        }
      }
      return docId;
    } catch (e) {
      debugPrint('Export Error: $e');
      return null;
    } finally {
      isSyncing = false;
      notifyListeners();
    }
  }
}
