// ═══════════════════════════════════════════════════════════
// ARIA SYSTEM — Category & Query Templates
// 25 Categories covering Tamil Nadu, India, World, and more
// ═══════════════════════════════════════════════════════════

enum AriaCategory {
  // World
  sports,
  technology,
  news,
  science,
  finance,
  health,
  environment,
  culture,
  // India & Tamil Nadu
  tamilnaduNews,
  tamilMovies,
  tamilMusic,
  indiaNews,
  indianPolitics,
  indianSports,
  indianBusiness,
  // Entertainment
  bollywood,
  movieRelease,
  musicGlobal,
  gaming,
  // Lifestyle
  food,
  travel,
  education,
  // Regional
  keralaNews,
  karnatakaNews,
  andhraTelanganaNews,
}

class CategoryConstants {
  CategoryConstants._();

  // ── Human-readable labels
  static const Map<AriaCategory, String> labels = {
    AriaCategory.sports: '🏆 Sports',
    AriaCategory.technology: '💻 Technology',
    AriaCategory.news: '📰 World News',
    AriaCategory.science: '🔬 Science',
    AriaCategory.finance: '💰 Finance',
    AriaCategory.health: '🏥 Health',
    AriaCategory.environment: '🌍 Environment',
    AriaCategory.culture: '🎭 Culture',
    AriaCategory.tamilnaduNews: '🌴 Tamil Nadu News',
    AriaCategory.tamilMovies: '🎬 Tamil Movies (Kollywood)',
    AriaCategory.tamilMusic: '🎵 Tamil Music',
    AriaCategory.indiaNews: '🇮🇳 India News',
    AriaCategory.indianPolitics: '🏛️ Indian Politics',
    AriaCategory.indianSports: '🏏 Indian Sports',
    AriaCategory.indianBusiness: '📈 Indian Business',
    AriaCategory.bollywood: '🎬 Bollywood',
    AriaCategory.movieRelease: '🍿 Movie Releases',
    AriaCategory.musicGlobal: '🎶 Global Music',
    AriaCategory.gaming: '🎮 Gaming',
    AriaCategory.food: '🍛 Food & Recipes',
    AriaCategory.travel: '✈️ Travel',
    AriaCategory.education: '📚 Education',
    AriaCategory.keralaNews: '🌊 Kerala News',
    AriaCategory.karnatakaNews: '🏙️ Karnataka News',
    AriaCategory.andhraTelanganaNews: '🌄 Andhra/Telangana News',
  };

  // ── Default query terms per category for trending fetch
  static const Map<AriaCategory, List<String>> defaultQueries = {
    AriaCategory.sports: [
      'breaking sports news today',
      'cricket news today',
      'IPL 2025 latest news',
      'football results today',
      'tennis news today',
    ],
    AriaCategory.technology: [
      'latest technology news today 2025',
      'AI artificial intelligence news India',
      'smartphone release 2025',
      'cybersecurity news today',
      'startup funding India news',
    ],
    AriaCategory.news: [
      'breaking world news today',
      'international news update',
      'USA news today',
      'UK news latest',
      'Europe news today',
    ],
    AriaCategory.science: [
      'scientific discovery news today',
      'NASA space news 2025',
      'ISRO news India',
      'medical research breakthrough',
      'astronomy news today',
    ],
    AriaCategory.finance: [
      'stock market news today India',
      'Sensex Nifty today',
      'cryptocurrency news India',
      'RBI news today',
      'Indian economy news',
    ],
    AriaCategory.health: [
      'health news India today',
      'WHO health update 2025',
      'disease outbreak news India',
      'Ayush medical news',
      'mental health news India',
    ],
    AriaCategory.environment: [
      'climate change India news today',
      'Tamil Nadu weather today',
      'flood news India today',
      'renewable energy India news',
      'pollution news India',
    ],
    AriaCategory.culture: [
      'Tamil culture festival news',
      'Pongal celebration news',
      'Indian classical music news',
      'South Indian art news today',
      'cultural festival Tamil Nadu',
    ],
    AriaCategory.tamilnaduNews: [
      'Tamil Nadu news today',
      'Chennai latest news today',
      'Tamil Nadu government news',
      'Coimbatore Madurai news today',
      'Tamil Nadu politics news',
      'Tamil Nadu crime news today',
      'AIADMK DMK news today',
      'Tamil Nadu education news',
      'Tamil Nadu weather news',
      'Tamil Nadu sports news',
    ],
    AriaCategory.tamilMovies: [
      'Kollywood Tamil movie news today',
      'Tamil movie release 2025',
      'Vijay Thalapathy latest movie news',
      'Ajith latest movie news',
      'Tamil movie box office today',
      'Kollywood actor news today',
      'Tamil OTT release today',
      'Sun TV Star Vijay serial news',
      'Tamil movie review today',
      'Kamal Haasan Rajinikanth news',
    ],
    AriaCategory.tamilMusic: [
      'Tamil music new song release today',
      'AR Rahman latest music news',
      'Anirudh new song today',
      'Tamil album release 2025',
      'Tamil music chart today',
      'Tamil kuthu song today',
      'Yuvan Shankar Raja news',
      'Tamil independent music news',
    ],
    AriaCategory.indiaNews: [
      'India news today breaking',
      'Indian government news today',
      'Delhi news today latest',
      'India economy news 2025',
      'India foreign relations news',
      'Modi government news today',
      'India budget news',
      'India army news today',
    ],
    AriaCategory.indianPolitics: [
      'BJP Congress news today India',
      'Indian election news 2025',
      'Parliament session news India',
      'Chief Minister news India',
      'state election results India',
      'India politics latest update',
    ],
    AriaCategory.indianSports: [
      'cricket India match today',
      'IPL score today',
      'Indian hockey news today',
      'Virat Kohli Rohit Sharma news',
      'Indian football news today',
      'badminton chess news India',
      'BCCI news India today',
    ],
    AriaCategory.indianBusiness: [
      'Indian startup news today',
      'BSE NSE stock news today',
      'TATA Reliance Infosys news',
      'Make in India news',
      'India GDP news today',
      'Indian tech company news',
    ],
    AriaCategory.bollywood: [
      'Bollywood movie news today',
      'Hindi movie box office today',
      'Bollywood actor latest news',
      'SRK Salman Aamir movie news',
      'Bollywood OTT release today',
      'Bollywood music new release',
    ],
    AriaCategory.movieRelease: [
      'new movie release this week India',
      'Hollywood movie release 2025',
      'South Indian movie release today',
      'Netflix Amazon Prime new movies India',
      'upcoming movie trailer today',
    ],
    AriaCategory.musicGlobal: [
      'Billboard Hot 100 today',
      'new music release Friday',
      'Grammy awards news',
      'Spotify trending songs today',
      'global music chart today',
    ],
    AriaCategory.gaming: [
      'gaming news today 2025',
      'PUBG FreeFire news India',
      'PlayStation Xbox release news',
      'esports tournament news India',
      'mobile gaming news today',
    ],
    AriaCategory.food: [
      'food news India today',
      'Tamil Nadu food festival',
      'recipe trending today India',
      'hotel restaurant news Chennai',
      'Indian cuisine food trend 2025',
    ],
    AriaCategory.travel: [
      'travel news India today',
      'Tamil Nadu tourism news',
      'flight train news India',
      'Indian Railways news today',
      'travel restrictions India 2025',
    ],
    AriaCategory.education: [
      'education news India today',
      'Tamil Nadu school college news',
      'NEET JEE exam news 2025',
      'TN board exam news',
      'scholarship news India 2025',
      'IIT IIM admission news',
    ],
    AriaCategory.keralaNews: [
      'Kerala news today latest',
      'Kerala politics news',
      'Kerala flood rain news',
      'Kochi news today',
      'Kerala government news',
    ],
    AriaCategory.karnatakaNews: [
      'Karnataka news today',
      'Bengaluru Bangalore news today',
      'Karnataka politics news',
      'Karnataka government news',
      'Kannada entertainment news',
    ],
    AriaCategory.andhraTelanganaNews: [
      'Andhra Pradesh news today',
      'Telangana news today',
      'Hyderabad news latest',
      'Telugu entertainment news today',
      'AP Telangana politics news',
    ],
  };

  // ── Poll cadence per category (seconds)
  static const Map<AriaCategory, int> pollCadenceSeconds = {
    AriaCategory.tamilnaduNews: 60, // BREAKING - Tamil Nadu live
    AriaCategory.sports: 60, // BREAKING - live scores
    AriaCategory.indianSports: 60,
    AriaCategory.news: 60, // BREAKING - breaking news
    AriaCategory.indiaNews: 60,
    AriaCategory.indianPolitics: 120,
    AriaCategory.tamilMovies: 300,
    AriaCategory.tamilMusic: 300,
    AriaCategory.bollywood: 300,
    AriaCategory.finance: 300, // STANDARD - market data
    AriaCategory.indianBusiness: 300,
    AriaCategory.technology: 900,
    AriaCategory.health: 900,
    AriaCategory.movieRelease: 900,
    AriaCategory.keralaNews: 600,
    AriaCategory.karnatakaNews: 600,
    AriaCategory.andhraTelanganaNews: 600,
    AriaCategory.gaming: 1800,
    AriaCategory.food: 3600,
    AriaCategory.travel: 3600,
    AriaCategory.education: 3600,
    AriaCategory.environment: 1800,
    AriaCategory.science: 3600,
    AriaCategory.musicGlobal: 1800,
    AriaCategory.culture: 21600,
  };

  // ── Time limits for news freshness (DDG parameter)
  // 'd' = last 24h, 'w' = last week, 'm' = last month
  static const Map<AriaCategory, String> timeLimit = {
    AriaCategory.tamilnaduNews: 'd',
    AriaCategory.sports: 'd',
    AriaCategory.indianSports: 'd',
    AriaCategory.news: 'd',
    AriaCategory.indiaNews: 'd',
    AriaCategory.indianPolitics: 'd',
    AriaCategory.tamilMovies: 'd',
    AriaCategory.tamilMusic: 'd',
    AriaCategory.bollywood: 'd',
    AriaCategory.finance: 'd',
    AriaCategory.indianBusiness: 'd',
    AriaCategory.keralaNews: 'd',
    AriaCategory.karnatakaNews: 'd',
    AriaCategory.andhraTelanganaNews: 'd',
    AriaCategory.technology: 'w',
    AriaCategory.health: 'w',
    AriaCategory.movieRelease: 'w',
    AriaCategory.environment: 'w',
    AriaCategory.gaming: 'w',
    AriaCategory.food: 'w',
    AriaCategory.travel: 'w',
    AriaCategory.education: 'w',
    AriaCategory.musicGlobal: 'w',
    AriaCategory.science: 'm',
    AriaCategory.culture: 'm',
  };
}
